project:
  type: website

website:
  navbar:
    logo: "assets/logo.svg"
    logo-alt: "Hushh.ai"
    logo-href: "https://www.hush.ai"
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true


