project:
  type: website
  output-dir: docs

execute:
  freeze : true


website:
  title: "Hushh Labs"
  favicon: "assets/fav-icon.ico"
  google-analytics: "G-WBK4GY6RXB"
  site-url: "https://hushh-labs.github.io/hushh-labs-blog/"
  margin-header: subscribe.html
  navbar:
    logo: "assets/logo.svg"
    logo-alt: "Hushh.ai"
    logo-href: "https://www.hushh.ai"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: rss
        href: index.xml

format:
  html:
    theme: pulse
    css: styles.css
    toc: true


