project:
  type: website
  output-dir: public

website:
  title: "Hushh Labs"
  favicon: "assets/fav-icon.ico"
  google-analytics: "G-WBK4GY6RXB"
  site-url: "https://hushh_labs.gitlab.io/gitlab-profile/"
  navbar:
    logo: "assets/logo.svg"
    logo-alt: "Hushh.ai"
    logo-href: "https://hush1one.com/"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: rss
        href: index.xml

format:
  html:
    theme: lux
    css: styles.css
    toc: true


