name: Build and Publish

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      QUARTO_VERSION: "1.3.433"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install wget ca-certificates
          wget "https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.deb" -O quarto.deb
          sudo dpkg -i quarto.deb

      - name: Build and render
        run: quarto render . --output-dir docs

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
